[package]
name = "admin"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.24", features = ["tokio-comp"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["v4"] }
